pipeline {
    agent {
        docker {
            image 'build-zulu-openjdk:11'
            label 'docker'
            registryUrl 'https://engineering-docker.software.r3.com/'
            registryCredentialsId 'artifactory-credentials'
            args '-v /tmp:/host_tmp'
            alwaysPull true
        }
    }

    environment {
          GRADLE_USER_HOME = "/host_tmp/gradle"
     }

    stages {
        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
        stage('Publish Image') {
                    steps {
                        sh './gradlew :http:snoop-wrap:jib'
                    }
                }
    }
}
