pipeline {
    agent { label 'docker' }

    stages {
        stage('Test') {
            steps {
                sh './gradlew -version'
                sh './gradlew test'
            }
        }
    }
}
